<a href="https://colab.research.google.com/github/Deepan-mn/Machine_learning_Libraries/blob/main/NumPy_Practices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy <br>
The NumPy (Numeric python) library is the core library for scientific computing 
in python. It provides a high-performance multidimensional array object, and tools for working with arrays

**Use the Following import convention**

In [18]:
import  numpy as np

## Creating Arrays 

In [ ]:
a = np.array([1,2,3])  # one dimension array
b = np.array([[1,2,3,],[4,5,6]])  # two dimesion array
c = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=float)
print("The one dimension arrray:",a)
print("The two dimension array:",end='\n')
print(b)
print("The Three dimension array with specified data type(float)",end="\n")
print(c)


The one dimension arrray: [1 2 3]
The two dimension array:
[[1 2 3]
 [4 5 6]]
The Three dimension array with specified data type(float)
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Initial Placeholders

**Creating an array of zeros**

In [ ]:
a = np.zeros((3,4),dtype=float)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Creating an array of ones**

In [ ]:
a = np.ones((3,4),dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


**Creating an array of evenly spaced values(step value)**

In [ ]:
a = np.arange(10,50,5) # 10 to <50 , increment by 5
print(a)

[10 15 20 25 30 35 40 45]


**Creating an array of evenly spaced values(number of samples)**

In [ ]:
a = np.linspace(0,2,9) # 0 to 2 , equally divided by 9
print(a)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


**Create a Constant array**

In [ ]:
a = np.full((2,2),7)
print(a)

[[7 7]
 [7 7]]


**Create a Identity matrix**

In [ ]:
a = np.eye(4,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Create an empty array with random values** 

In [ ]:
a = np.random.random((3,3))
print(a)

[[0.98720522 0.99518426 0.62825213]
 [0.79791066 0.53197438 0.36197143]
 [0.34247892 0.71572754 0.26441901]]


**Create an empty array**

In [ ]:
a = np.empty((3,2))
print(a)

[[4.64595217e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


## Input / Output Handling in NumPy

**Saving & Loading On Disk**

In [ ]:
a = np.array([1,2,3])
x = np.array([4,5,6])

b = np.save('new_array',a) # to save a one numpy array to one file

c =np.savez('array.npz',name1=a,name2=x) # to save a multiple numpy array to one file

d =np.load('/content/new_array.npy')
e =np.load('/content/array.npz')

print("The loaded file :: save ",end='\n')
print(d)
print("The loaded file :: savez ",end='\n')
print(e['name1'])
print(e['name2'])

The loaded file :: save 
[1 2 3]
The loaded file :: savez 
[1 2 3]
[4 5 6]


**Saving & Loading Text Files**

In [ ]:
x = np.loadtxt('/content/test_text',delimiter=",") # deals with unpacking the file
y = np.genfromtxt('/content/test_text.csv',delimiter=",") # deals with missing values and filling values
a = np.savetxt("new_text.txt",x, delimiter=" ")

print("The loaded data ::test_text.txt",end='\n')
print(x)
print("The loaded data ::test_text.csv",end='\n')
print(y)

The loaded data ::test_text.txt
[1. 2. 3.]
The loaded data ::test_text.csv
[1. 2. 3.]


## Data Types

In [ ]:
np. int64     #  signed 64 bit integer types
np.float32     #  Standard double-precision floating point
np.complex     # Complex numbers represented by 128 floats
np.bool        # Boolean type storing TRUE and FALSE values
np.object      # Python object type
np.string_      # Fixed-length string type
np.unicode     # Fixed-length unicode type   

str

## Inspecting the Array

**Array Dimensions**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

print("The shape of the array",a.shape)

The shape of the array (2, 6)


**Length of array**

In [ ]:
a = np.array([1,2,3,4,5,6])

print("The length of array:",len(a))

The length of array: 6


**Number of array dimensions**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

print("The dimension of array:",a.ndim)

The dimension of array: 2


**Number of array elements**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

print("The number of elements present:",a.size)

The number of elements present: 12


**Data type of array elements**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

print("The data type is :",a.dtype)

The data type is : int64


**Convert an array to different type**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

a = a.astype(float)

print(a)

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]]


## Array Mathematics

## Arithmetic Operations

**Subtraction**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.ones((2,6))

c = a-b 
print(c)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]


**Subtraction**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.ones((2,6))

c = np.subtract(a,b)
print(c)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]


**Addition**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.ones((2,6))

c = a+b
print(c)

[[ 2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13.]]


**Addition**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.ones((2,6))

c = np.add(a,b)
print(c)

[[ 2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13.]]


**Division**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.ones((2,6))

c = a/b
print(c)

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]]


**Division**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.ones((2,6))

c = np.divide(a,b)
print(c)

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]]


**Multiplication**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.full((2,6),2)

c = a*b
print(c)

[[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]]


**Multiplication**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.full((2,6),2)

c = np.multiply(a,b)
print(c)

[[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]]


**Exponentiation**

In [ ]:
a = np.array([1,3,5])

c =np.exp(a)   # e =2.71828183 , e power the array elements
print("The exponentiation:", c)

The exponentiation: [  2.71828183  20.08553692 148.4131591 ]


**Square Root**

In [ ]:
a =np.array([9,49,81])

c =np.sqrt(a)
print(c)

[3. 7. 9.]


**Element-wise Sines of an array**

In [ ]:
a =np.array([0,60,90])

c =np.sin(a)
print("The sine values are:",c )

The sine values are: [ 0.         -0.30481062  0.89399666]


**Element-wise cosines of an array**

In [ ]:
a = np.array([0,60,90])

c =np.cos(a)
print("The cosine values are: ",c)

The cosine values are:  [ 1.         -0.95241298 -0.44807362]


**Element-wise Natural Logarithm**

In [ ]:
a = np.array([4,5,6])

c =np.log(a)
print("The log values are:",c)

The log values are: [1.38629436 1.60943791 1.79175947]


In [ ]:
a = np.ones((3,3))
b = np.ones((3,3))

c =a.dot(b)
print("The dot product is :",c)

The dot product is : [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


##Comparison

**Element-wise Comparsion**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.array([[1,2,3,4,5,6],[7,0,9,10,11,1]])

a == b

array([[ True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True, False]])

**Element-wise Comparsion**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

a < 2

array([[ True, False, False, False, False, False],
       [False, False, False, False, False, False]])

**Array-wise Comparsion**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b = np.array([[1,2,3,4,5,6],[7,0,9,10,11,1]])

c = np.array_equal(a,b)
print(c)

False


##Aggregate Fuctions

**Array-wise sum**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

a.sum()

78

**Array-wise minimum value**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

a.min()

1

**Maximum value of an array row**

In [ ]:
a = np.array([1,2,3,4,5,6])

a.max(axis=0) # 1 = column 0 =row

6

**Cumulative sum of the elements**

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

a.cumsum(axis=1)

array([[ 1,  3,  6, 10, 15, 21],
       [ 7, 15, 24, 34, 45, 57]])

**Mean**

In [21]:
a = np.array([1,2,3,4,5,6])


a.mean()

3.5

**Correlation coefficient**

In [32]:
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])

np.correlate(a,b) #This function computes the correlation as generally defined
# in signal processing texts: c_{av}[k] = sum_n a[n+k] * conj(v[n])

array([217])

**Median**

In [35]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

np.median(a)

6.5

**Standard deviation**

In [36]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

np.std(a)

3.452052529534663

##Copying Arrays

**Create a view of the array with the same data**

In [38]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

h =a.view()
print(h)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


**Create a copy of the array**

In [39]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

b = np.copy(a)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


**Create a deep copy of the array**

In [40]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

b = a.copy()
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


##Sorting Arrays

**Sort an array**

In [43]:
a =np.array([12,11,10,9,8])

a.sort()
print(a)

[ 8  9 10 11 12]


**Sort the elements of an array's axis**

In [44]:
a =np.array([[2, 2, 2, 2, 2],  
       [15, 6, 27, 8, 2], 
       [23, 2, 54, 1, 2, ], 
       [11, 44, 34, 7, 2]] )

a.sort(axis=0)
print(a)

[[ 2  2  2  1  2]
 [11  2 27  2  2]
 [15  6 34  7  2]
 [23 44 54  8  2]]


##Subsetting,Slicing,Indexing

##Subsetting

**Select the element at the 2nd index**

In [49]:
a = np.array([1,2,3,4,5,6])

print(a[2])


3


**Select the element at row 0 column 2(equivalent to a[1][2])**

In [52]:
a = np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12]])

a[1,2]

9

##Slicing

**Select items at index 0 and 1**

In [51]:
a = np.array([1,2,3,4,5,6])

a[0:2]

array([1, 2])

**Select items at rows 0 and 1 in column 1**

In [53]:
a = np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12]])

a[0:2, 1]

array([2, 8])

**Select all items at row 0 (equivalent to b[0:1 , :])**

In [54]:
a = np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12]])

a[:1]

array([[1, 2, 3, 4, 5, 6]])

**Same as [1, : , :]**

In [56]:
a = np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12]])

a[1,...]

array([ 7,  8,  9, 10, 11, 12])

**Reversed array**

In [58]:
a = np.array([1,2,3,4,5,6])

a[: :-1]

array([6, 5, 4, 3, 2, 1])

##Boolean Indexing

**Select elements from a less than 2**

In [59]:
a = np.array([1,2,3,4,5,6])

a[a<4]

array([1, 2, 3])

##Fancy Indexing

**Select elements (1,0),(0,1),(1,2) and (0,0)**

In [66]:
a = np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12]])
a[(1,0,1,0),(0,1,2,0)]

array([7, 2, 9, 1])

**Select a subset of the matrix's rows and columns**

In [68]:
a =np.array([[2, 2, 2, 2, 2],  
       [15, 6, 27, 8, 2], 
       [23, 2, 54, 1, 2, ], 
       [11, 44, 34, 7, 2]] )


a[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[15,  6, 27, 15],
       [ 2,  2,  2,  2],
       [15,  6, 27, 15],
       [ 2,  2,  2,  2]])

##Array Manipulation

##Transposing Array

**Permute array dimensions**

In [69]:
a =np.array([[2, 2, 2, 2, 2],  
       [15, 6, 27, 8, 2], 
       [23, 2, 54, 1, 2, ], 
       [11, 44, 34, 7, 2]] )

np.transpose(a)

array([[ 2, 15, 23, 11],
       [ 2,  6,  2, 44],
       [ 2, 27, 54, 34],
       [ 2,  8,  1,  7],
       [ 2,  2,  2,  2]])

**Permute array dimensions**

In [70]:
a =np.array([[2, 2, 2, 2, 2],  
       [15, 6, 27, 8, 2], 
       [23, 2, 54, 1, 2, ], 
       [11, 44, 34, 7, 2]] )

a.T

array([[ 2, 15, 23, 11],
       [ 2,  6,  2, 44],
       [ 2, 27, 54, 34],
       [ 2,  8,  1,  7],
       [ 2,  2,  2,  2]])

##Changing Array Shape

**Flatten the Array**

In [71]:
a =np.array([[2, 2, 2, 2, 2],  
       [15, 6, 27, 8, 2], 
       [23, 2, 54, 1, 2, ], 
       [11, 44, 34, 7, 2]] )

a.ravel()

array([ 2,  2,  2,  2,  2, 15,  6, 27,  8,  2, 23,  2, 54,  1,  2, 11, 44,
       34,  7,  2])

**Reshape, but don't change data**

In [76]:
a =np.array([[2, 2, 2, 2, 2],  
       [15, 6, 27, 8, 2], 
       [23, 2, 54, 1, 2, ], 
       [11, 44, 34, 7, 2]] )
a.reshape((5,4))

array([[ 2,  2,  2,  2],
       [ 2, 15,  6, 27],
       [ 8,  2, 23,  2],
       [54,  1,  2, 11],
       [44, 34,  7,  2]])

##Adding/Removing Element

**Return a new array with shape (2,6)**

In [78]:
a =np.array([[2, 2, 2, 2, 2],  
       [15, 6, 27, 8, 2], 
       [23, 2, 54, 1, 2, ], 
       [11, 44, 34, 7, 2]] )

a.resize(10,2)
print(a)

[[ 2  2]
 [ 2  2]
 [ 2 15]
 [ 6 27]
 [ 8  2]
 [23  2]
 [54  1]
 [ 2 11]
 [44 34]
 [ 7  2]]


**Append items to an array**

In [83]:
a = np.arange(8).reshape(2,4)
b = np.arange(8,16).reshape(2,4)

c = np.append(a,b,axis=0) # 1 = column
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


**Insert items in an array**

In [87]:
a =np.array([[2, 2, 2, 2, 2],  
       [15, 6, 27, 8, 2], 
       [23, 2, 54, 1, 2, ], 
       [11, 44, 34, 7, 2]] )

np.insert(a, 1 , 0,axis=1)

array([[ 2,  0,  2,  2,  2,  2],
       [15,  0,  6, 27,  8,  2],
       [23,  0,  2, 54,  1,  2],
       [11,  0, 44, 34,  7,  2]])

**Delete items from an array**

In [93]:
a = np.arange(8)

np.delete(a,4)

array([0, 1, 2, 3, 5, 6, 7])

##Combining Arrays

**Concantenate arrays**

In [94]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [97]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

**Stack arrays vertically (row-wise)**

In [99]:
a = np.array([1, 2])
b = np.array([5, 6])

np.vstack((a,b))

array([[1, 2],
       [5, 6]])

**Stack arrays vertically (row-wise)**

In [101]:
a = np.array([1, 2])
b = np.array([5, 6])

np.r_[a,b]

array([1, 2, 5, 6])

**Stack arrays horizontally (column-wise)**

In [102]:
a = np.array([1, 2])
b = np.array([5, 6])

np.hstack((a,b))

array([1, 2, 5, 6])

**Create stacked column-wise arrays**

In [103]:
a = np.array([1, 2])
b = np.array([5, 6])

np.column_stack((a,b))

array([[1, 5],
       [2, 6]])

**Create stacked column-wise arrays**

In [104]:
a = np.array([1, 2])
b = np.array([5, 6])

np.c_[a,b]

array([[1, 5],
       [2, 6]])

##Splitting Arrays

**Split the array horizontally at the 3rd index**

In [112]:
a =np.array([[2, 2, 2, 2, 2],  
       [15, 6, 27, 8, 2], 
       [23, 2, 54, 1, 2, ], 
       [11, 44, 34, 7, 2]] )

np.hsplit(a,5)

[array([[ 2],
        [15],
        [23],
        [11]]), array([[ 2],
        [ 6],
        [ 2],
        [44]]), array([[ 2],
        [27],
        [54],
        [34]]), array([[2],
        [8],
        [1],
        [7]]), array([[2],
        [2],
        [2],
        [2]])]

**Split the array vertically at the 2nd index**

In [115]:
a =np.array([[2, 2, 2, 2, 2],  
       [15, 6, 27, 8, 2], 
       [23, 2, 54, 1, 2, ], 
       [11, 44, 34, 7, 2]] )

np.vsplit(a,2)

[array([[ 2,  2,  2,  2,  2],
        [15,  6, 27,  8,  2]]), array([[23,  2, 54,  1,  2],
        [11, 44, 34,  7,  2]])]